meta_product_name: "at-home"
meta_title: "at-home | Building connections through food"
meta_description: "This app will help you find your cooking buddy close to you, so that you can cook anywhere you travel"
meta_image: "image-home.png"
meta_url: "https://www.at-home.gold"
